-- MySQL Script generated by MySQL Workbench
-- Thu May 25 19:23:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital` ;
USE `hospital` ;

-- -----------------------------------------------------
-- Table `hospital`.`Departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Departments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Doctor` (
  `employeeId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NULL,
  `Departments_id` INT NULL,
  PRIMARY KEY (`employeeId`),
  UNIQUE INDEX `id_UNIQUE` (`employeeId` ASC) VISIBLE,
  INDEX `fk_Doctor_Departments1_idx` (`Departments_id` ASC) VISIBLE,
  CONSTRAINT `fk_Doctor_Departments1`
    FOREIGN KEY (`Departments_id`)
    REFERENCES `hospital`.`Departments` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`PatientMedicalChart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`PatientMedicalChart` (
  `reportId` INT NOT NULL AUTO_INCREMENT,
  `diagnosis` VARCHAR(45) NULL,
  `date` DATE NULL,
  PRIMARY KEY (`reportId`),
  UNIQUE INDEX `reportId_UNIQUE` (`reportId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Nurse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Nurse` (
  `employeeId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NULL,
  `Departments_id` INT NULL,
  PRIMARY KEY (`employeeId`),
  UNIQUE INDEX `id_UNIQUE` (`employeeId` ASC) VISIBLE,
  INDEX `fk_Nurse_Departments1_idx` (`Departments_id` ASC) VISIBLE,
  CONSTRAINT `fk_Nurse_Departments1`
    FOREIGN KEY (`Departments_id`)
    REFERENCES `hospital`.`Departments` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Insurance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Insurance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `expirationDate` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idInsurance_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Patient` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL,
  `phoneNumber` VARCHAR(45) NULL,
  `Doctor_employeeId` INT NOT NULL,
  `PatientMedicalChart_reportId` INT NOT NULL,
  `Nurse_employeeId` INT NOT NULL,
  `Insurance_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Patient_Doctor_idx` (`Doctor_employeeId` ASC) VISIBLE,
  INDEX `fk_Patient_PatientMedicalChart1_idx` (`PatientMedicalChart_reportId` ASC) VISIBLE,
  INDEX `fk_Patient_Nurse1_idx` (`Nurse_employeeId` ASC) VISIBLE,
  INDEX `fk_Patient_Insurance1_idx` (`Insurance_id` ASC) VISIBLE,
  CONSTRAINT `fk_Patient_Doctor`
    FOREIGN KEY (`Doctor_employeeId`)
    REFERENCES `hospital`.`Doctor` (`employeeId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Patient_PatientMedicalChart1`
    FOREIGN KEY (`PatientMedicalChart_reportId`)
    REFERENCES `hospital`.`PatientMedicalChart` (`reportId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Patient_Nurse1`
    FOREIGN KEY (`Nurse_employeeId`)
    REFERENCES `hospital`.`Nurse` (`employeeId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Patient_Insurance1`
    FOREIGN KEY (`Insurance_id`)
    REFERENCES `hospital`.`Insurance` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Medication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Medication` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `brand` VARCHAR(45) NULL,
  `dose` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Treatment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Treatment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idTreatment_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Appointment` (
  `id` INT NOT NULL,
  `date` DATE NULL,
  `time` TIME NULL,
  `Patient_id` INT NULL,
  PRIMARY KEY (`id`, `Patient_id`),
  INDEX `fk_Appointment_Patient1_idx` (`Patient_id` ASC) VISIBLE,
  CONSTRAINT `fk_Appointment_Patient1`
    FOREIGN KEY (`Patient_id`)
    REFERENCES `hospital`.`Patient` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`MedicalBill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`MedicalBill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amountDue` DECIMAL(4) NULL,
  `Patient_id` INT NULL,
  `Insurance_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Patient_id`, `Insurance_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_MedicalBill_Patient1_idx` (`Patient_id` ASC) VISIBLE,
  INDEX `fk_MedicalBill_Insurance1_idx` (`Insurance_id` ASC) VISIBLE,
  CONSTRAINT `fk_MedicalBill_Patient1`
    FOREIGN KEY (`Patient_id`)
    REFERENCES `hospital`.`Patient` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_MedicalBill_Insurance1`
    FOREIGN KEY (`Insurance_id`)
    REFERENCES `hospital`.`Insurance` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Lab`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Lab` (
  `id` INT NOT NULL,
  `testName` VARCHAR(45) NULL,
  `cost` DECIMAL(4) NULL,
  `Patient_id` INT NULL,
  PRIMARY KEY (`id`, `Patient_id`),
  INDEX `fk_Lab_Patient1_idx` (`Patient_id` ASC) VISIBLE,
  CONSTRAINT `fk_Lab_Patient1`
    FOREIGN KEY (`Patient_id`)
    REFERENCES `hospital`.`Patient` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Symptoms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Symptoms` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Doctor_has_Appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Doctor_has_Appointment` (
  `Doctor_employeeId` INT NOT NULL,
  `Appointment_id` INT NOT NULL,
  `Appointment_Patient_id` INT NOT NULL,
  PRIMARY KEY (`Doctor_employeeId`, `Appointment_id`, `Appointment_Patient_id`),
  INDEX `fk_Doctor_has_Appointment_Appointment1_idx` (`Appointment_id` ASC, `Appointment_Patient_id` ASC) VISIBLE,
  INDEX `fk_Doctor_has_Appointment_Doctor1_idx` (`Doctor_employeeId` ASC) VISIBLE,
  CONSTRAINT `fk_Doctor_has_Appointment_Doctor1`
    FOREIGN KEY (`Doctor_employeeId`)
    REFERENCES `hospital`.`Doctor` (`employeeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doctor_has_Appointment_Appointment1`
    FOREIGN KEY (`Appointment_id` , `Appointment_Patient_id`)
    REFERENCES `hospital`.`Appointment` (`id` , `Patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Nurse_has_Appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Nurse_has_Appointment` (
  `Nurse_employeeId` INT NOT NULL,
  `Appointment_id` INT NOT NULL,
  `Appointment_Patient_id` INT NOT NULL,
  PRIMARY KEY (`Nurse_employeeId`, `Appointment_id`, `Appointment_Patient_id`),
  INDEX `fk_Nurse_has_Appointment_Appointment1_idx` (`Appointment_id` ASC, `Appointment_Patient_id` ASC) VISIBLE,
  INDEX `fk_Nurse_has_Appointment_Nurse1_idx` (`Nurse_employeeId` ASC) VISIBLE,
  CONSTRAINT `fk_Nurse_has_Appointment_Nurse1`
    FOREIGN KEY (`Nurse_employeeId`)
    REFERENCES `hospital`.`Nurse` (`employeeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nurse_has_Appointment_Appointment1`
    FOREIGN KEY (`Appointment_id` , `Appointment_Patient_id`)
    REFERENCES `hospital`.`Appointment` (`id` , `Patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`PatientMedicalChart_has_Symptoms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`PatientMedicalChart_has_Symptoms` (
  `PatientMedicalChart_reportId` INT NOT NULL,
  `Symptoms_id` INT NOT NULL,
  PRIMARY KEY (`PatientMedicalChart_reportId`, `Symptoms_id`),
  INDEX `fk_PatientMedicalChart_has_Symptoms_Symptoms1_idx` (`Symptoms_id` ASC) VISIBLE,
  INDEX `fk_PatientMedicalChart_has_Symptoms_PatientMedicalChart1_idx` (`PatientMedicalChart_reportId` ASC) VISIBLE,
  CONSTRAINT `fk_PatientMedicalChart_has_Symptoms_PatientMedicalChart1`
    FOREIGN KEY (`PatientMedicalChart_reportId`)
    REFERENCES `hospital`.`PatientMedicalChart` (`reportId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PatientMedicalChart_has_Symptoms_Symptoms1`
    FOREIGN KEY (`Symptoms_id`)
    REFERENCES `hospital`.`Symptoms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`PatientMedicalChart_has_Treatment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`PatientMedicalChart_has_Treatment` (
  `PatientMedicalChart_reportId` INT NOT NULL,
  `Treatment_id` INT NOT NULL,
  PRIMARY KEY (`PatientMedicalChart_reportId`, `Treatment_id`),
  INDEX `fk_PatientMedicalChart_has_Treatment_Treatment1_idx` (`Treatment_id` ASC) VISIBLE,
  INDEX `fk_PatientMedicalChart_has_Treatment_PatientMedicalChart1_idx` (`PatientMedicalChart_reportId` ASC) VISIBLE,
  CONSTRAINT `fk_PatientMedicalChart_has_Treatment_PatientMedicalChart1`
    FOREIGN KEY (`PatientMedicalChart_reportId`)
    REFERENCES `hospital`.`PatientMedicalChart` (`reportId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PatientMedicalChart_has_Treatment_Treatment1`
    FOREIGN KEY (`Treatment_id`)
    REFERENCES `hospital`.`Treatment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`Medication_has_PatientMedicalChart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`Medication_has_PatientMedicalChart` (
  `Medication_id` INT NOT NULL,
  `PatientMedicalChart_reportId` INT NOT NULL,
  PRIMARY KEY (`Medication_id`, `PatientMedicalChart_reportId`),
  INDEX `fk_Medication_has_PatientMedicalChart_PatientMedicalChart1_idx` (`PatientMedicalChart_reportId` ASC) VISIBLE,
  INDEX `fk_Medication_has_PatientMedicalChart_Medication1_idx` (`Medication_id` ASC) VISIBLE,
  CONSTRAINT `fk_Medication_has_PatientMedicalChart_Medication1`
    FOREIGN KEY (`Medication_id`)
    REFERENCES `hospital`.`Medication` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medication_has_PatientMedicalChart_PatientMedicalChart1`
    FOREIGN KEY (`PatientMedicalChart_reportId`)
    REFERENCES `hospital`.`PatientMedicalChart` (`reportId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
